sudo: required
language: python

services:
  - docker

before_install:
  - sudo apt-get update
  - chmod +x nginx/nginx.sh

script:
  - rm -y /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker-compose up --build -d
  - docker ps

install:
  - pip install -r requirements.txt