sudo: required
language: python

services:
  - docker

before_install:
  - sudo apt-get update
  - chmod +x nginx/nginx.sh

script:
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - docker-compose --version
  - docker-compose up --build -d
  - docker ps
  - pytest nginx/webtest.py

install:
  - pip install -r requirements.txt