sudo: required
language: python

env:
  - MOZ_HEADLESS=1
  
addons:
  firefox: latest

before_install:
  - chmod +x nginx/nginx.sh
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -xvzf geckodriver-v0.24.0-linux64.tar.gz
  - chmod +x geckodriver
  - sudo mv geckodriver /usr/local/bin
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - docker-compose --version
  - pip install -r requirements.txt

script:
  - docker-compose up --build -d
  - docker-compose ps
  - python flask/flasktest.py
  - docker-compose logs