version: "3.3"
services:
  flaskserv:
    build: ./flask
    ports:
      - "5555:5555"
    links:
      - "mariadb"
  mariadb:
    image: mariadb:10
    container_name: mariadb
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: RobClem19920902_
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  