#
# Drew Gallis
# CSEC 380
# Nginx Dockerfile Config File
#

# Pulling latest nginx image
FROM nginx:1.29.4-alpine3.23

# Updating index file with correct html file
COPY index.html /usr/share/nginx/html/